document.addEventListener('DOMContentLoaded', () => {
    const form = document.getElementById('registrationForm');
    const submitBtn = form.querySelector('.submit-btn');
    const btnText = submitBtn.querySelector('.btn-text');
    const btnLoader = submitBtn.querySelector('.btn-loader');
    const successMessage = document.getElementById('successMessage');
    const errorMessage = document.getElementById('errorMessage');

    // Google Apps Script Web App URL - YOU NEED TO CREATE THIS
    // Instructions: See SETUP.md for how to create the Google Apps Script
    const GOOGLE_APPS_SCRIPT_URL = 'YOUR_GOOGLE_APPS_SCRIPT_URL_HERE';

    form.addEventListener('submit', async (e) => {
        e.preventDefault();

        // Hide messages
        successMessage.style.display = 'none';
        errorMessage.style.display = 'none';

        // Disable button and show loader
        submitBtn.disabled = true;
        btnText.style.display = 'none';
        btnLoader.style.display = 'inline';

        // Get form data
        const formData = {
            prenume: document.getElementById('prenume').value.trim(),
            nume: document.getElementById('nume').value.trim(),
            nume_complet: document.getElementById('prenume').value.trim() + ' ' + document.getElementById('nume').value.trim(),
            email: document.getElementById('email').value.trim(),
            telefon: document.getElementById('telefon').value.trim(),
            data_nasterii: document.getElementById('data_nasterii').value || '',
            referred_by: document.getElementById('referred_by').value.trim() || '',
            gdpr: document.getElementById('gdpr').checked ? 'DA' : 'NU',
            categorie: 'Standard', // Default category
            discount_vin: '0%', // Default discount
            discount_produse: '0%', // Default discount
            cod_client: '', // Will be generated by Google Sheets
            activ: 'NU', // Initially not active
            necesita_aprobare: 'DA', // Needs approval
            timestamp: new Date().toISOString()
        };

        try {
            const response = await fetch(GOOGLE_APPS_SCRIPT_URL, {
                method: 'POST',
                mode: 'no-cors', // Required for Google Apps Script
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify(formData)
            });

            // Note: With no-cors, we can't read the response
            // We assume success if no error is thrown
            successMessage.style.display = 'block';
            form.reset();

            // Scroll to success message
            successMessage.scrollIntoView({ behavior: 'smooth', block: 'center' });

        } catch (error) {
            console.error('Error:', error);
            errorMessage.style.display = 'block';
            errorMessage.scrollIntoView({ behavior: 'smooth', block: 'center' });
        } finally {
            // Re-enable button
            submitBtn.disabled = false;
            btnText.style.display = 'inline';
            btnLoader.style.display = 'none';
        }
    });
});
